### ISSUE TITLE
gradle not able to resolve jersey-unit:1.0.1

### ISSUE THREAD

**Issue by bogdan-marian** [hanleyt/jersey-junit#4]
I have to configure the client in order to register the MultiPartBeanProvider.class. I can see that [this issue is closed](https://github.com/hanleyt/jersey-junit/issues/1)  but at the moment gradle is "Unable to resolve com.github.hanley:jersey-unit:1.0.1". It can only resolve 1.0.0 witch does not provide client configuration features. For the moment the only way that I can get pass this problem is by installing the artifacts in the local maven cache.

**Comment by hanleyt** [comment]
hey @bogdan-marian,

Sorry about the late reply, I was having too good a Christmas break and I forgot to get back to you!

Thanks for bringing this up. It turns out I forgot to publish the 1.0.1 release on github and jitpack wasn't able to pick up the version to build it.

 It should be available now if you retry.

Thanks,
Tom

**Comment by bogdan-marian** [comment]
Thanks so much. I stooped using the local cache and everything resolves properly. :+1:
